apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mod8-sc-high-throughput
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  encrypted: "true"
  type: gp3
  throughput: "300"
