apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-env
data:
  PROD_ENV_DB_HOST: proddb.database.com
  PROD_ENV_DB_TIMEOUT: '10'
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prod-config
data:
  config.ini: |
    val1:1
    val2:2
---
apiVersion: v1
kind: Secret
metadata:
  name: accountlogin
type: Opaque
data:
  username: bXl1c2VybmFtZQo=
  password: bXlwYXNzd29yZAo=
---
apiVersion: v1
kind: Pod
metadata:
  name: mod01-pod-config-env
spec:
  containers:
    - name: centos
      image: centos:8
      command: ["/sbin/init"]
      env:
      - name: ENV_FROM_POD_MAN
        value: "Hello from pod manifest"
      envFrom:
      - configMapRef:
          name: prod-env
      - secretRef:
          name: accountlogin
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: prod-config
